version: "3.9"
services:

  stup-service:
    build:
      context: .
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789